blank_issues_enabled: false
contact_links:
  - name: PaperMod Discussions
    url: https://github.com/0Ky/hugo-PaperFlow/discussions
    about: Please ask and answer questions/doubts here, DO NOT open an issue for questions.
